### ISSUE TITLE
github login name 换过之后会生成新的账户

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spmjs.io#101]
比如偏右发现的这个账户：http://spmjs.io/account/Janus-Z

根据 id 判断，而不是 login 判断。
https://github.com/spmjs/spmjs.io/blob/master/models/account.js#L11

**Comment by afc163** [comment]
较为彻底的解决方案：

1. 修改所有根据 login 查询用户的逻辑为根据 id 查询。
2. 修改所有包的 index.json 里的 owner 字段：

```json
"owner": ["user1", "user2"],
```

改为

```json
"owner": [{
  "name": "user1",
  "id": "12345"
}, {
  "name": "user2",
  "id": "12346"
}],
```
