### ISSUE TITLE
spm unpublish后web页面还有残余信息，npm run reindex也无效果

### ISSUE THREAD

**Issue by kulwe** [spmjs/spmjs.io#112]
搭建私有源的过程遇到一些坑，package.json中script指定的pm2路径固定的，以前用-g安装过pm2，这个简单修改就ok，只是不知道base.yaml中的authorize怎么设置？
```
authorize:
    type: 'anonymous' # or github
```
改为
```
authorize:
    type: 'github' # or github
```
最后就是如标题，publish tools后，在web页面看到了tools，但是执行unpublis 取消所有版本后，仍然能在web端看到tools。npm run reindex也不见效果

**Comment by afc163** [comment]
https://github.com/spmjs/spmjs.io/pull/81

**Comment by afc163** [comment]
可以在服务端由管理员进行较为彻底的删除：https://github.com/spmjs/spmjs.io/blob/20a0f089aae95a04921187628cc38bac70be31af/scripts/unpublish.js

**Comment by kulwe** [comment]
多谢回复，感觉该更新下README.md吧？

**Comment by afc163** [comment]
每个版本都有很多改动，请自行关注：https://github.com/spmjs/spmjs.io/blob/master/History.md
