### ISSUE TITLE
npm run postinstall 且 npm run postinstall 报错

### ISSUE THREAD

**Issue by peter-sun** [spmjs/spmjs.io#113]
─────────────┬────┬──────┬───────┬────────┬───────────┬────────┬─────────────┬──────────┐
│ App name      │ id │ mode │ PID   │ status │ restarted │ uptime │      memory │ watching │
├───────────────┼────┼──────┼───────┼────────┼───────────┼────────┼─────────────┼──────────┤
│ spmjs         │ 0  │ fork │ 17970 │ online │       118 │ 0s     │ 20.305 MB   │ disabled │
│ elasticsearch │ 1  │ fork │ 18000 │ online │        61 │ 0s     │  3.766 MB   │ disabled │
│ spmjs         │ 2  │ fork │ 17974 │ online │       884 │ 0s     │ 23.266 MB   │ disabled │
│ elasticsearch │ 3  │ fork │ 18001 │ online │        46 │ 0s     │  3.770 MB   │ disabled │
└───────────────┴────┴──────┴───────┴────────┴───────────┴────────┴─────────────┴──────────┘
 Use `pm2 info <id|name>` to get more details about an app
[root@gitlab spmjs.io]# npm run reindex

> spmjs.io@1.4.0-dev reindex /root/download/spmjs.io
> node scripts/reindexPackages.js

Deleted index spmjs.
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
[root@gitlab spmjs.io]# npm run postinstall
npm ERR! Linux 2.6.32-358.el6.x86_64
npm ERR! argv "node" "/root/.linuxbrew/bin/npm" "run" "postinstall"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0

npm ERR! missing script: postinstall
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/download/spmjs.io/npm-debug.log

**Comment by peter-sun** [comment]
这个和jdk版本有关吗？

**Comment by afc163** [comment]
请按照 Readme.md 文档进行操作。。

最好先理解下运行的命令的功能。

**Comment by peter-sun** [comment]
jdk版本问题
