### ISSUE TITLE
spm3.x   不为seajs服务啊？ 下载的包不是cmd的，要自己改造吗？ spm2.0用惯了！！

### ISSUE THREAD

**Issue by honger05** [spmjs/spmjs.io#120]

**Comment by honger05** [comment]
下载的包不是cmd的，要自己改造吗？ spm2.0用惯了！！

**Comment by popomore** [comment]
构建成 cmd 的

**Comment by afc163** [comment]
源码是 CommonJS 的。

https://github.com/spmjs/spm/issues/819
http://segmentfault.com/q/1010000002466503

**Comment by honger05** [comment]
spm2.x会被关掉吗？

**Comment by popomore** [comment]
有问题还是会修复的

**Comment by honger05** [comment]
![image](https://cloud.githubusercontent.com/assets/8788044/6521606/d06696f0-c414-11e4-8f81-38c39dbcd430.png)

**Comment by honger05** [comment]
" 所以，是的，使用 spm3 可以而且推荐不使用 seajs 。"

那我想使用seajs，是不是用spm2好一些呢？

正如seajs官网说的，使用spm2构建工具，合并打包等功能。spm build就能发布到本地dist目录。
而spm3 使用spm build命令则要发布到源上，我并不想发布到源上。因为我想要的是像grunt一样的合并打包工具。

**Comment by popomore** [comment]
build 不会发源。。。2/3 都支持构建成 CMD，不知道你具体遇到什么问题？

**Comment by honger05** [comment]
请教一个问题，比如我用seajs做项目，我现在想用backbone，我用spm2拿下来的backbone已经改造成cmd的了，直接就能用。
![image](https://cloud.githubusercontent.com/assets/8788044/6522887/33f9fc92-c425-11e4-9021-deb053a99ff1.png)

而我用spm3拿下来的，需要自己手动改造。这样是不是说我用spm2更适合做seajs的项目呢？
![image](https://cloud.githubusercontent.com/assets/8788044/6522897/4b395074-c425-11e4-835e-346aac42f931.png)

**Comment by afc163** [comment]
http://sorrycc.gitbooks.io/spm-handbook/content/develop-package/README.html
