### ISSUE TITLE
无法安装提示elasticsearch不兼容要降版本

### ISSUE THREAD

**Issue by hiwanz** [spmjs/spmjs.io#127]
> npm ERR! Linux 2.6.18-308.el5
> npm ERR! argv "node" "/usr/local/bin/npm" "install"
> npm ERR! node v0.10.26
> npm ERR! npm  v2.4.1
> npm ERR! code ETARGET
> 
> npm ERR! notarget No compatible version found: elasticsearch-package@'>=1.4.3 <2.0.0'
> npm ERR! notarget Valid install targets:
> npm ERR! notarget ["1.4.2"]
> npm ERR! notarget 
> npm ERR! notarget This is most likely not a problem with npm itself.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ued/spmjs.io/npm-debug.log

**Comment by afc163** [comment]
`npm info elasticsearch-package` 的结果如下，版本都是存在。

```json
{ name: 'elasticsearch-package',
  description: 'Download elasticsearch package from npm',
  'dist-tags': { latest: '1.4.3' },
  versions: [ '1.4.2', '1.4.3' ],
  maintainers: [ 'afc163 <afc163@gmail.com>', 'sorrycc <sorrycc@gmail.com>' ],
  time: 
   { modified: '2015-03-11T06:11:59.520Z',
     created: '2014-12-26T07:17:51.465Z',
     '1.4.2': '2014-12-26T07:17:51.465Z',
     '1.4.3': '2015-03-11T06:11:59.520Z' },
  homepage: 'https://github.com/afc163/elasticsearch-package',
  keywords: [ 'elasticsearch', 'download', 'package', 'zip' ],
  repository: 
   { type: 'git',
     url: 'git@github.com:afc163/elasticsearch-package.git' },
  bugs: { url: 'https://github.com/afc163/elasticsearch-package/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.4.3',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  author: '',
  gitHead: '60c83f065cd0e2451e2fba8e3f38ee0d98fc5a10',
  dist: 
   { shasum: '015fc75e9c81acf7bbdc660b0a653dc4d0b891cd',
     tarball: 'http://registry.npmjs.org/elasticsearch-package/-/elasticsearch-package-1.4.3.tgz' },
  directories: {} }
```

建议楼主更新 `spmjs.io` 到最新版，然后试试：

 ```
rm -rf node_modules
npm cache clean
npm install
```

**Comment by afc163** [comment]
另外，是否是从官方源安装的？

**Comment by hiwanz** [comment]
换了源重新install就可以了，多谢。
