### ISSUE TITLE
打包代码时，不能得到如期结果，不知道问题在哪里？

### ISSUE THREAD

**Issue by ken1987** [spmjs/spmjs.io#130]
package.json

{
	"name": "test",
	"version": "1.1.0",
	"spm": {
		"main": "test.js",
		"buildArgs": {
			"dest":"dist",
			"include":"umd"
		}
	}
}

test.js

define(function(require) {var a = require("./a"), b = require("./b");});

a.js

define(function() {return "a";});

b.js

define(function() {return "b";});

smp build 的结果：
![image](https://cloud.githubusercontent.com/assets/7424698/7017841/fbaedf78-dd2f-11e4-96fe-8ed39aa7ba58.png)

我的理解,按照http://sorrycc.gitbooks.io/spm-handbook/content/package.json/buildArgs.html
里面介绍的，应该得到如下结果，
test_110_a_debug=(function(){}());
不应该还包含着define关键字，不知道我的问题在哪里？

**Comment by afc163** [comment]
请使用 CommonJS 规范来书写代码。

**Comment by ken1987** [comment]
@afc163 按照CommonJS 来写可以实现功能。
但是，目前我的项目里面有大量的seajs模块，我希望开发过程中依然使用seajs的写法，功能测试好后，用spm来打包压缩这些代码。
请问有没有解决途径。

**Comment by afc163** [comment]
只能用 spm2

**Comment by ken1987** [comment]
@afc163 谢谢。我去试试。
