### ISSUE TITLE
spmjs.io 又挂了一天

### ISSUE THREAD

**Issue by hotoo** [spmjs/spmjs.io#136]
http://spmjs.io/ 502 Bad Gateway

**Comment by popomore** [comment]
加个监控宝吧
闲耘™ <notifications@github.com>于2015年4月19日 周日上午8:50写道：

**Comment by afc163** [comment]
有监控宝，免费版只能通知一个人。

**Comment by afc163** [comment]
最近一直挂掉的原因是这个：https://github.com/spmjs/spm/issues/1260

**Comment by popomore** [comment]
用 cluster 吧，挂了重新 fork 一个，可以先找个模块用用
偏右 <notifications@github.com>于2015年4月19日 周日下午2:32写道：

**Comment by sorrycc** [comment]
@popomore 现在的数据库不支持 cluster，等换成 mysql 时一起改成 cluster 。

**Comment by sorrycc** [comment]
早上又挂了，重启了下机器，今天观察下。(感觉每次重启机器后都能稳定一段时间)
