### ISSUE TITLE
我这边修改了配置文件，但好像没效果，求解

### ISSUE THREAD

**Issue by x-manJS** [spmjs/spmjs.io#154]
求教

whitelistOnly: off 之前我设为on，然后我没办法publish了，现在我改回了on，但还是不能publish。
是不是有缓存呢？有缓存的话改怎么清除呢，我stop了也没效果。

还是其他原因呢?

**Comment by x-manJS** [comment]
publish时的显示：

 publish: ttt2@1.0.0
  target: http://192.168.252.137:3000/
    exit: ~ ~ http://192.168.252.137:3000//repository/ttt2/1.0.0/

**Comment by max-lai** [comment]
删除 data/repository/tt2，再publish就可以了

**Comment by x-manJS** [comment]
ok~
