### ISSUE TITLE
spm doc publish的问题

### ISSUE THREAD

**Issue by kxbrand** [spmjs/spmjs.io#63]
我刚才发布了一个包，http://spmjs.io/docs/superslide/latest/examples/index.html
example里面用的是iframe来调用的示例，但是spm doc publish上去后，iframe里面的页面有的打进去了，有的没打进去，不知道是怎么一回事。

**Comment by popomore** [comment]
upload 是原来的逻辑?

**Comment by kxbrand** [comment]
最近没再测试呢，等测试完再反馈。。，先关闭问题了，谢谢。
