### ISSUE TITLE
用 markdown-it 代替 marked

### ISSUE THREAD

**Issue by afc163** [spmjs/spmjs.io#89]
[marked](https://github.com/chjj/marked) 长期无人维护，在某些情况下有严重性能问题，已经人神公愤。

发现一个 [markdown-it](https://github.com/markdown-it/markdown-it)，经本地测试（ http://spmjs.io/package/ion-rangeslider ），表现良好。

**Comment by fengmk2** [comment]
呃，真够变态的，npmjs.com 上直接将这个模块删除了。。。 https://www.npmjs.com/package/ion-rangeslider

**Comment by fengmk2** [comment]
markdown-it 要升级到 3.0.0, 要不然还是会有问题

**Comment by fengmk2** [comment]
果然会挂 https://www.npmjs.com/package/ion-rangeslider-test , npmwww 用的是 marked

**Comment by fengmk2** [comment]
![](http://ww2.sinaimg.cn/large/61c56ebcjw1enxz0c6us7j20i609cdh5.jpg)
