### ISSUE TITLE
markdown 解析问题

### ISSUE THREAD

**Issue by sorrycc** [spmjs/spmjs.io#95]
http://spmjs.io/package/rc-calendar

![image](https://cloud.githubusercontent.com/assets/35128/5628860/a04b5984-95e7-11e4-91d5-abc8205d3b94.png)

**Comment by afc163** [comment]
这是 Github 的解析逻辑，无解。

建议写成 `[![]()]()` 标准的 Markdown 格式。

**Comment by yiminghe** [comment]
https://github.com/react-component/calendar 

github 是好的

**Comment by afc163** [comment]
嗯，这是 GFM 的特性。

之前因为性能问题从 marked 切到 markdown-it 。 https://github.com/spmjs/spmjs.io/issues/89

但是 markdown-it 对 GFM 的支持不好，难道又要切回去。。。

要不维护一个分支版本，改改性能问题好了。

**Comment by sorrycc** [comment]
https://github.com/GitbookIO/kramed
这个能用吗?

**Comment by afc163** [comment]
目测和 marked 一样

**Comment by afc163** [comment]
Fork 一个 kramed 好了，好歹这还在维护。

**Comment by afc163** [comment]
https://github.com/GitbookIO/kramed/pull/9 有人维护就是好...

**Comment by fengmk2** [comment]
悲剧。。。 kramed 还是 marked 。。。

**Comment by fengmk2** [comment]
还是会被攻击

**Comment by fengmk2** [comment]
这个功能很容易就在 markdown-it 实现了

**Comment by afc163** [comment]
有实现代码吗？

还有这个 html 格式的问题：https://github.com/markdown-it/markdown-it/issues/26

主要是 GFM 对兼容性做的比较多。

**Comment by fengmk2** [comment]
我晚上看看

**Comment by fengmk2** [comment]
反正无论如何都不能使用 marked
